arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-dir: lib/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales: ["zh"]
synthetic-package: false
nullable-getter: false
header: |
  // ignore_for_file: non_constant_identifier_names 