name: jlpt_app
description: 'JLPT Study App'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_markdown: ^0.6.18
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  uuid: ^4.5.1
  email_validator: ^2.1.17
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/audio/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: zh
  arb_dir: lib/l10n
  output_dir: lib/generated
